[project]
name = 'Decentralized-Traditional-Food-Preservation-Knowledge-System-PR-Details'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.knowledge-transfer]
path = 'contracts/knowledge-transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.seasonal-scheduling]
path = 'contracts/seasonal-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.technique-registration]
path = 'contracts/technique-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
